import { createElement } from 'lwc';
import LwcBulkRoomF1417 from 'c/lwcBulkRoomF1417';

describe('c-lwc-bulk-room-f-1417', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-bulk-room-f-1417', {
            is: LwcBulkRoomF1417
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});